from .files import SurveyModeChoiceResultsFile
from .mode_choice import SurveyEconometricModeChoiceStep
from .preferences import ModePreferencesFromEconometricsStep

ECONOMETRICS_FILES = [SurveyModeChoiceResultsFile]

ECONOMETRICS_STEPS = [SurveyEconometricModeChoiceStep, ModePreferencesFromEconometricsStep]
