from .files import (
    NonPrimaryCarTrips,
    PrimaryCarTripsAccessEgressFile,
    TripsBicycleCostsFile,
    TripsBicycleNodesFile,
    TripsCarFreeFlowTravelTimesFile,
    TripsPedestrianDistancesFile,
    TripsPedestrianNodesFile,
    TripsPublicTransitItinerariesFile,
    TripsRoadNodesFile,
    ZonesLevel1MedoidsFile,
    ZonesLevel1RoadNodeFile,
    ZonesLevel2MedoidsFile,
    ZonesLevel2RoadNodeFile,
    ZonesLevel3MedoidsFile,
    ZonesLevel3RoadNodeFile,
    ZonesLevel4MedoidsFile,
    ZonesLevel4RoadNodeFile,
    ZonesLevel5MedoidsFile,
    ZonesLevel5RoadNodeFile,
)
from .od_pairs import (
    BicycleODNodesFromCoordinatesStep,
    PedestrianODNodesFromCoordinatesStep,
    RoadODNodesFromCoordinatesStep,
)
from .od_zones import (
    ZonesLevel1MedoidsStep,
    ZonesLevel1RoadNodesStep,
    ZonesLevel2MedoidsStep,
    ZonesLevel2RoadNodesStep,
    ZonesLevel3MedoidsStep,
    ZonesLevel3RoadNodesStep,
    ZonesLevel4MedoidsStep,
    ZonesLevel4RoadNodesStep,
    ZonesLevel5MedoidsStep,
    ZonesLevel5RoadNodesStep,
)
from .opentripplanner import TripsOpenTripPlannerStep
from .r5 import TripsPublicTransitTravelTimeFromR5Step
from .road_split import CarAccessEgressStep, RoadNetworkPrimaryEdgesStep
from .routing_cli import (
    TripsBicycleCostStep,
    TripsCarFreeFlowTravelTimesStep,
    TripsPedestrianDistancesStep,
)

ROUTING_FILES = [
    TripsPedestrianNodesFile,
    TripsPedestrianDistancesFile,
    TripsBicycleNodesFile,
    TripsBicycleCostsFile,
    TripsRoadNodesFile,
    TripsCarFreeFlowTravelTimesFile,
    PrimaryCarTripsAccessEgressFile,
    TripsPublicTransitItinerariesFile,
    NonPrimaryCarTrips,
    ZonesLevel1RoadNodeFile,
    ZonesLevel2RoadNodeFile,
    ZonesLevel3RoadNodeFile,
    ZonesLevel4RoadNodeFile,
    ZonesLevel5RoadNodeFile,
    ZonesLevel1MedoidsFile,
    ZonesLevel2MedoidsFile,
    ZonesLevel3MedoidsFile,
    ZonesLevel4MedoidsFile,
    ZonesLevel5MedoidsFile,
]

ROUTING_STEPS = [
    PedestrianODNodesFromCoordinatesStep,
    BicycleODNodesFromCoordinatesStep,
    RoadODNodesFromCoordinatesStep,
    TripsPedestrianDistancesStep,
    TripsBicycleCostStep,
    TripsCarFreeFlowTravelTimesStep,
    RoadNetworkPrimaryEdgesStep,
    CarAccessEgressStep,
    TripsOpenTripPlannerStep,
    TripsPublicTransitTravelTimeFromR5Step,
    ZonesLevel1RoadNodesStep,
    ZonesLevel2RoadNodesStep,
    ZonesLevel3RoadNodesStep,
    ZonesLevel4RoadNodesStep,
    ZonesLevel5RoadNodesStep,
    ZonesLevel1MedoidsStep,
    ZonesLevel2MedoidsStep,
    ZonesLevel3MedoidsStep,
    ZonesLevel4MedoidsStep,
    ZonesLevel5MedoidsStep,
]
